main: dev.themeinerlp.faweschematiccloud.FAWESchematicCloud
name: FAWESchematicCloud
version: 1.3.0
depend:
  - 'FastAsyncWorldEdit'
api-version: '1.21'
commands:
  /schemdownload:
    description: Downloads a schematic
    usage: //schemdownload
  /schemload:
    description: Loads a schematic
    usage: //schemload
  /schemloadall:
    description: Loads all schematics
    usage: //schemloadall
  /schemclear:
    description: Clears a schematic
    usage: //schemclear
  /schemunload:
    description: Unloads a schematic
    usage: //schemunload
  /schemmove:
    description: Moves a schematic
    usage: //schemmove
  /schemsave:
    description: Saves a schematic
    usage: //schemsave
  /schemformats:
    description: Lists schematic formats
    usage: //schemformats
  /schemlist:
    description: Lists all schematics
    usage: //schemlist
  /schemdel:
    description: Deletes a schematic
    usage: //schemdel
