main: work.alsace.faweschematiccloud.FAWESchematicCloud
name: FAWESchematicCloud
version: 1.3.0
depend:
  - 'FastAsyncWorldEdit'
api-version: '1.17'
commands:
  /download:
    description: Downloads a schematic
    usage: //download
  /schem:
    description: Loads a schematic
    usage: //schem load
